### PR TITLE
Added support for specifying HTTP and HTTPS bindings on IIS sites

### PR DESCRIPTION
**Pull request by laazyj**
Have a look at https://github.com/laazyj/dropkick/blob/master/product/dropkick.tests/TestObjects/IisHttpsSiteDeploy.cs for a look at how it works.

There are also some other changes related to IIS7 operations.

J

### CODE REVIEW

**Comment by ferventcoder** [comment]
Love that you have quite a few commits - would love to see the pull request from from a branch folder though...so when you move forward later we don't run into commit bleed.

**Comment by laazyj** [comment]
I'm pretty new to GitHub. Could you give me some tips on how you'd like to receive pull requests in the future?

**Comment by ferventcoder** [comment]
do the work for a pull request in a branch. Push the branch to github. Do the pull request from the branch. Make sense?

**Comment by laazyj** [comment]
Gotcha. You ok for these changes or would you like me to re-present them
differently?

On 22 February 2012 17:32, Rob Reynolds <
reply@reply.github.com

**Comment by ferventcoder** [comment]
I haven't had a chance to look at them yet...

**Comment by drusellers** [comment]
Hi Laazyj,

I pulled down your repo and took a look. You have an awefully lot of work that I would hate to waste, and here is what you will want to do, to get everything going. I hope I have this correct. ;)
1. git remote add chuck git://github.com/chucknorris/dropkick.git
2. git rebase chuck/master
3. fix any merge conflicts
4. git checkout -b my_feature #now you have a feature branch
5. Run tests
6. fix tests
7. make sure you are update date w/ us by running step 1 again.
8. submit pull request. 
9. Smile :)

Note: I see you did a merge, we may have to do some surgery to fix that.

**Comment by drusellers** [comment]
I know that merge is going to cause some issues, if you get stuck give me a holler.

**Comment by jcornell** [comment]
Hey guys, has this made it any closer to making into chucknorris:master?  I might be able to help if needed...

**Pull request closed without merging**
