### PR TITLE
Added possibility to specify profile(s) on the NServiceBusHost options

### PR DESCRIPTION
**Pull request by thedersen**

### CODE REVIEW

**Comment by ferventcoder** [comment]
Did I miss something? Why did you close the pull request?

**Comment by thedersen** [comment]
I changed the commit range in pull request #29 so it doesn't include the reformatting, which resulted in two pull requests. Closed the first one so there wouldn't be a duplicate. Hope that's ok.

**Comment by ferventcoder** [comment]
Okay, awesome. I had forgotten that I commented on it. I appreciate the removal of the reformatting. That will allow us to bring in the pull request quicker.

**Comment by thedersen** [comment]
Cool:)

**Pull request merged**
