### PR TITLE
RavenDb as a windows service support

### PR DESCRIPTION
**Pull request by danielmarbach**
Added support to install ravendb server as a windows service. I hope this is compliant to the chuck norris style.

### CODE REVIEW

**Comment by danielmarbach** [comment]
Added additional support to uninstall ravendb server as windows service

**Comment by drusellers** [comment]
I am hesitant to add this as it is very RavenDB specific - is there a way this can just be a service install type task??? I am ultimately open to adding this, just need to be convinced. :)

**Comment by danielmarbach** [comment]
Hy
There is also stuff in there which is Nservicebus specific. This commit doesn't take any dependency to RavenDB so why not adding it?

**Comment by drusellers** [comment]
bah! I forgot about that NSB stuff (not a fan of that either for the same reason) ok, i will review it again.

**Comment by danielmarbach** [comment]
Maybe it would be wise to create a contrib project and then move all the crazy stuff such as NSB and RavenDB into that project. This would allow more aggressiv release cycles

**Comment by drusellers** [comment]
Nah. Just more overhead for now. I will just add it in. Stuff is easy to move out if need be later. 

-d

**Comment by danielmarbach** [comment]
I will not complain ;)

**Comment by drusellers** [comment]
done 9ba2450cde8a69808c8f894d7dcef8059326572d

**Pull request closed without merging**
