### PR TITLE
Update Wmi and IisVirtualDirectory code to accept username and password

### PR DESCRIPTION
**Pull request by mmooney**
I've been trying to get dropkick setup to run as a step in a TeamCity build, to deploy from one Amazon VM to another.  The VMs are not in the same domain, so the user on the build server does not have any administrative rights on the target server, so we needed to be able to pass in an administrative username and password to open the WMI connection.

This creates a new WithAdministratorAccount method on IisVirtualDirectoryOptions, and passes that username and password all they down to WmiHelper.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Are you concerned about opening a security hole here?

**Comment by ferventcoder** [comment]
I don't see any updates to tests. Have you verified that this works?

**Comment by ferventcoder** [comment]
You would also need a way to actually pass the remote dropkick.exe file over to the other server. How do you propose to handle that?

**Comment by mmooney** [comment]
Hi Rob,

As far as potential security holes, this requires that you have a username and password for an administrative user on the remote machine.  If the person running it has those credentials available, I'd think that they should be able to do whatever they want to the machine, the same as if they were logged into a domain account that is an administrator on the remote machine.  This is an attempt to reasonably deal with the scenario of "yes I have administrative access to THAT machine over there, but it's through a different local admin account on that machine, so you're not going to trust my account over here on this machine, so here are my credentials for that machine".  I don't doubt that that in could introduce a security issue for someone a lot smarter than me, but I haven't been able to think of one yet.

As far as tests, I was looking for a good place to put a test for this, but since it's at the periphery and requires attempting to access another machine, I didn't see a good place for a relevant test.  Let me know if there is good place for that.

As far as it working, yes, I had to code this today to get my client's TeamCity auto-deploy working from one Amazon VM to another.  They are using successfully with the version from my fork as we speak :)

And right now this is just to be able to open up the WMI connection.  I seems like this scenario (administering another box outside your domain by providing a username and password instead of a trusted domain account) is doesn't have a whole lot of support in dropkick, but it's something regularly have a need for so I want to try to get it added, so hopefully I'll be submitting a lot more changes.  

For instance, I know that the ServerManager stuff all assumes that you're running on a trusted domain account, and that's the next thing I want to tackle.  That one is going to be tricky though, because it doesn't have "username" and "password" fields, so it will probably require some sort of impersonation.

Thanks

**Comment by mmooney** [comment]
So I made the mistake of submitting this from my master branch instead of a feature branch.  So when I merged my amazon S3 changes in, they came into this pull request. But I created a new branch just for these WMI changes, so I could resubmit another pull request with that branch if you want.

Thanks

**Comment by ferventcoder** [comment]
Please.

On Thursday, March 14, 2013, Mike Mooney wrote:

> So I made the mistake of submitting this from my master branch instead of
> a feature branch. So when I merged my amazon S3 changes in, they came into
> this pull request. But I created a new branch just for these WMI changes,
> so I could resubmit another pull request with that branch if you want.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chucknorris/dropkick/pull/56#issuecomment-14922814
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by mmooney** [comment]
Sure, will do.  Also you mentioned tests, that can be tricky because most of the WMI stuff is using static methods.  Should I refactor into some instance classes/methods so that I can test everything but the actual WMI connect call?

**Comment by ferventcoder** [comment]
Yeah, that might be helpful. Sorry about not paying attention to DK lately. I kind of thought the D man would pick on my slack // @drusellers

**Comment by mmooney** [comment]
Haha no problem, I know you guys are swamped in Chocolatey :).  I'll put something together and send over a new PR

**Comment by drusellers** [comment]
Oh hey. didn't even see this. @mmooney let me know when you are done and I can take a look. Note: I don't look at this project too much as I no longer use it. But I will try and jump on your PR when you get it done.

**Pull request closed without merging**
