### PR TITLE
BaseIoTask swallows exception

### PR DESCRIPTION
**Pull request by danielmarbach**
BaseIoTask swallows exceptions which can be very frustrating when you have access permission problems and want to find out the root cause

### CODE REVIEW

**Comment by ferventcoder** [comment]
Thanks...

**Comment by danielmarbach** [comment]
Any updates on this?

**Comment by danielmarbach** [comment]
Added two more commits:

f733610 is for better visibility when tasks are remote executed. You need to see the path
918a655 fixes a problem when a group contains spaces for example ...\ANONYMOUS LOGON that would lead to more command line arguments because the console automatically fills the args[] according to spaces

**Comment by drusellers** [comment]
:ship:

**Pull request merged**
