### PR TITLE
MS SQL SMO database task

### PR DESCRIPTION
**Pull request by pvasek**
We added a new DatabaseTask that use SMO objects. The unit tests are included. We needed to extend also dk.exe.config otherwise the SMO objects doesn't work correctly in 4.0 framework.

We tried to follow the style used in dropkick. If we should change something let us know.

We also add oneliner to fix LocalConsoleTask which completely ignored the ExecutableIsLocatedAt property.

### CODE REVIEW

**Comment by drusellers** [comment]
- DatabaseTask would need to be renamed to include MsSql or Smo in it somehow, as we will most likely support other db types.
- test app.config shouldn't have an app.config (hides test data away from the test)
- sql executions should not concat strings but use parameterized sql when possible
- need to check for the existance of SMO tools
- DatabaseTask.Name should be 'Runs SMO task Xxxxx' (use the verify to report all of that info)

**Comment by drusellers** [comment]
sorry, otherwise looking good! this will be a welcome addition.

**Comment by pvasek** [comment]
OK, no problem. I will try to fix that. 

regarding your comments:
- test app.config - in this case it is used only to hide differences between developers environments
- sql executions should not concat strings - that's clear but you can not use it for creating and dropping db, that's why it's used
- need to check for the existance of SMO tools - I am not sure here but looking to MSDN I would guess that, to have referenced assemblies in place is enough (http://msdn.microsoft.com/en-us/library/ms162167.aspx)

**Comment by drusellers** [comment]
yeah, re app.config - everyones test environment is different so the test data is best left in the test itself so the dev can see it and then mark the test as 'manual' or 'explicit' :(

ok, just stay vigilant. :)

looking for a dll, an exe, anything you can do in the verify step will help people debug the problem. its also nice to tell people how to fix it.

:)

**Pull request closed without merging**
